#!/usr/bin/env python
"""
Problem Statement:
     Each new term in the Fibonacci sequence is generated by adding the 
     previous two terms. By starting with 1 and 2, the first 10 terms will be:
                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     By considering the terms in the Fibonacci sequence whose values do not 
     exceed four million, find the sum of the even-valued terms.
"""

def print_fibona():
   num1, num2 = 0, 1
   next_fib_num = 0
   sum = 0;
   
   while next_fib_num < 4000000:
       next_fib_num = num1 + num2
       num1 = num2
       num2 = next_fib_num
       if next_fib_num % 2 == 0:
          sum = sum + next_fib_num
   print "The sum of all even fibonacci nos till 4 million is: ", sum

if __name__ == '__main__':
   print_fibona()
